apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
    - port: 80 # So we don't need to specify the port within our app
      targetPort: 8080
  type: LoadBalancer
