server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://postgres:5432/notification
    username: pekka
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://zipkin:9411/
  # Inform Spring where rabbitMQ lives
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false #Turning off Eureka server, since kubernetes offers service discovery for free

# Properties for our message queue
rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue # Queue identifier
  routing-keys:
    internal-notification: internal.notification.routing-key