spring:
  application:
    name: api-gateway
  zipkin:
    # old: http://localhost:9411/ new: container name
    base-url: http://zipkin:9411/
  # Gateway config
  cloud:
    gateway:
      #List of routes
      routes:
        - id: CUSTOMER
          uri: lb://CUSTOMER # Distributes the request to the appropriate customer node
          predicates:
            - Path=/api/v1/customers/**
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true